

const data = {
    Basic: [
        { id: "Layout", name: "布局" },
        { id: "Container", name: "布局容器" },
        { id: "Color", name: "色彩" },
        { id: "Typography", name: "字体" },
        { id: "Border", name: "边框" },
        { id: "Icon", name: "图标" },
        { id: "Button", name: "按钮" },
        { id: "Link", name: "文字链接" },
    ],
    Form: [
        { id: "Radio", name: "单选框" },
        { id: "Checkbox", name: "多选框" },
        { id: "Input", name: "输入框" },
        { id: "InputNumber", name: "计数器" },
        { id: "Select", name: "选择器" },
        { id: "Cascader", name: "级联选择器" },
        { id: "Switch", name: "开关" },
        { id: "Slider", name: "滑块" },
        { id: "TimePicker", name: "时间选择器" },
        { id: "DatePicker", name: "日期选择器" },
        { id: "DateTimePicker", name: "日期时间选择器" },
        { id: "Upload", name: "上传" },
        { id: "Rate", name: "评分" },
        { id: "ColorPicker", name: "颜色选择器" },
        { id: "Transfer", name: "穿梭框" },
        { id: "Form", name: "表单" },
    ],
    Data: [
        { id: "Table", name: "表格" },
        { id: "Tag", name: "标签" },
        { id: "Progress", name: "进度条" },
        { id: "Tree", name: "树形控件" },
        { id: "Pagination", name: "分页" },
        { id: "Badge", name: "标记" },
        { id: "Avatar", name: "头像" },
        { id: "Skeleton", name: "骨架屏" },
        { id: "Empty", name: "空状态" },
    ],
    Notice: [
        { id: "Alert", name: "警告" },
        { id: "Loading", name: "加载" },
        { id: "Message", name: "消息提示" },
        { id: "MessageBox", name: "弹框" },
        { id: "Notification", name: "通知" },
    ],
    Navigation: [
        { id: "NavMenu", name: "导航菜单" },
        { id: "Tabs", name: "标签页" },
        { id: "Breadcrumb", name: "面包屑" },
        { id: "PageHeader", name: "页头" },
        { id: "Dropdown", name: "下拉菜单" },
        { id: "Steps", name: "步骤条" },
    ],
    Others: [
        { id: "Dialog", name: "对话框" },
        { id: "Tooltip", name: "文字提示" },
        { id: "Popover", name: "弹出框" },
        { id: "Popconfirm", name: "气泡确认框" },
        { id: "Card", name: "卡片" },
        { id: "Carousel", name: "走马灯" },
        { id: "Collapse", name: "折叠面板" },
        { id: "Timeline", name: "时间线" },
        { id: "Divider", name: "分割线" },
        { id: "Calendar", name: "日历" },
        { id: "Image", name: "图片" },
        { id: "Backtop", name: "回到顶部" },
        { id: "InfiniteScroll", name: "无限滚动" },
        { id: "Drawer", name: "抽屉" },
    ],
};
export default data;